service: earthquake
provider:
  name: aws
  runtime: nodejs14.x
  memorySize: 128
  timeout: 10
  stage: dev
  region: us-east-1

plugins:
  - serverless-webpack
  - serverless-offline

functions:
  api:
    handler: handler.universal
    events:
      - http: ANY {proxy+}
      - http: ANY /

custom:
    webpack:
      webpackConfig: 'webpack.config.js'
      includeModules: false